package integrador;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/Sebas/Desktop/Lexico.flex

import java_cup.runtime.Symbol;
import jflex.core.sym;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\336\u0200\1\u0400\u1000\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\0\1\1\22\0\1\1\1\2\1\3"+
    "\1\4\1\5\1\6\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\12\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\2\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\41\1\47\1\50\1\51"+
    "\6\41\1\52\1\0\1\53\1\0\1\54\1\0\1\55"+
    "\2\41\1\56\1\57\1\60\1\61\1\62\1\63\2\41"+
    "\1\64\1\41\1\65\4\41\1\66\1\41\1\67\1\41"+
    "\1\70\3\41\1\71\1\72\1\73\43\0\1\74\7\0"+
    "\1\41\3\0\1\41\5\0\1\41\6\0\1\41\4\0"+
    "\1\75\2\0\1\76\1\41\235\0\1\41\u01ba\0\1\41"+
    "\23\0\1\41\u01cc\0\1\41\2\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\11\30\1\31\1\32\1\33\2\30\1\34\1\35"+
    "\1\36\1\1\1\0\1\37\1\40\1\0\1\41\1\0"+
    "\1\42\1\43\1\44\1\45\7\30\1\46\5\30\1\47"+
    "\1\50\1\0\3\30\1\51\2\30\1\52\3\30\1\7"+
    "\1\30\1\53\1\30\1\54\1\30\1\0\1\30\1\55"+
    "\7\30\1\0\1\30\1\56\1\30\1\57\1\30\1\60"+
    "\1\0\1\30\1\0\2\30\1\61\1\0\1\62\1\0"+
    "\1\30\1\63\2\0\1\30\2\0\1\30\2\0\1\64"+
    "\1\0\1\51\1\0\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\77\0\275\0\77\0\77\0\77"+
    "\0\77\0\77\0\77\0\77\0\77\0\77\0\77\0\374"+
    "\0\77\0\u013b\0\u017a\0\77\0\u01b9\0\u01f8\0\u0237\0\77"+
    "\0\77\0\u0276\0\u02b5\0\u02f4\0\u0333\0\u0372\0\u03b1\0\u03f0"+
    "\0\u042f\0\u046e\0\77\0\77\0\77\0\u04ad\0\u04ec\0\77"+
    "\0\77\0\77\0\u052b\0\275\0\77\0\374\0\374\0\77"+
    "\0\u056a\0\77\0\77\0\77\0\77\0\u05a9\0\u05e8\0\u0627"+
    "\0\u0666\0\u06a5\0\u06e4\0\u0723\0\u0276\0\u0762\0\u07a1\0\u07e0"+
    "\0\u081f\0\u085e\0\77\0\77\0\u089d\0\u08dc\0\u091b\0\u095a"+
    "\0\u0999\0\u09d8\0\u0a17\0\u0276\0\u0a56\0\u0a95\0\u0ad4\0\u0276"+
    "\0\u0b13\0\77\0\u0b52\0\u0276\0\u0b91\0\u0bd0\0\u0c0f\0\u0276"+
    "\0\u0c4e\0\u0c8d\0\u0ccc\0\u0d0b\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07"+
    "\0\u0e46\0\u0276\0\u0e85\0\u0276\0\u0ec4\0\u0276\0\u0f03\0\u0f42"+
    "\0\u0f81\0\u0fc0\0\u0fff\0\u0276\0\u103e\0\u0276\0\u107d\0\u10bc"+
    "\0\u0276\0\u10fb\0\u113a\0\u1179\0\u11b8\0\u11f7\0\u1236\0\u1275"+
    "\0\u12b4\0\u0276\0\u12f3\0\77\0\u1332\0\77";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\2\32\1\40"+
    "\5\32\1\41\1\32\1\42\1\32\1\43\1\44\1\45"+
    "\1\46\12\32\1\47\1\50\1\51\1\52\1\32\1\2"+
    "\1\53\100\0\1\3\76\0\1\54\1\0\1\55\14\0"+
    "\1\54\7\0\22\54\3\0\14\54\3\0\1\54\22\0"+
    "\1\56\74\0\1\57\1\0\1\22\102\0\1\60\71\0"+
    "\1\61\4\0\1\62\1\63\75\0\1\64\76\0\1\65"+
    "\72\0\1\32\7\0\22\32\2\0\15\32\3\0\1\32"+
    "\22\0\1\32\7\0\4\32\1\66\15\32\2\0\15\32"+
    "\3\0\1\32\22\0\1\32\7\0\7\32\1\67\12\32"+
    "\2\0\15\32\3\0\1\32\22\0\1\32\7\0\4\32"+
    "\1\70\15\32\2\0\15\32\3\0\1\32\22\0\1\32"+
    "\7\0\14\32\1\71\5\32\2\0\10\32\1\72\4\32"+
    "\3\0\1\32\22\0\1\32\7\0\12\32\1\73\7\32"+
    "\2\0\15\32\3\0\1\32\22\0\1\32\7\0\14\32"+
    "\1\74\5\32\2\0\4\32\1\75\1\76\7\32\3\0"+
    "\1\32\22\0\1\32\7\0\17\32\1\77\2\32\2\0"+
    "\15\32\3\0\1\32\22\0\1\32\7\0\21\32\1\100"+
    "\2\0\15\32\3\0\1\32\22\0\1\32\7\0\22\32"+
    "\2\0\11\32\1\101\3\32\3\0\1\32\22\0\1\32"+
    "\7\0\22\32\2\0\6\32\1\102\6\32\3\0\1\32"+
    "\76\0\1\103\1\104\1\0\17\61\1\105\57\61\20\0"+
    "\1\32\7\0\6\32\1\106\13\32\2\0\15\32\3\0"+
    "\1\32\22\0\1\32\7\0\1\107\21\32\2\0\15\32"+
    "\3\0\1\32\22\0\1\32\7\0\2\32\1\110\17\32"+
    "\2\0\15\32\3\0\1\32\22\0\1\32\7\0\3\32"+
    "\1\111\16\32\2\0\15\32\3\0\1\32\22\0\1\32"+
    "\7\0\22\32\2\0\12\32\1\112\2\32\3\0\1\32"+
    "\22\0\1\32\7\0\15\32\1\113\4\32\2\0\15\32"+
    "\3\0\1\32\22\0\1\32\7\0\21\32\1\114\2\0"+
    "\15\32\3\0\1\32\22\0\1\32\7\0\22\32\2\0"+
    "\13\32\1\115\1\32\3\0\1\32\22\0\1\32\7\0"+
    "\10\32\1\116\11\32\2\0\15\32\3\0\1\32\22\0"+
    "\1\32\7\0\17\32\1\117\2\32\2\0\15\32\3\0"+
    "\1\32\22\0\1\32\7\0\22\32\2\0\2\32\1\120"+
    "\12\32\3\0\1\32\22\0\1\32\7\0\22\32\2\0"+
    "\7\32\1\121\5\32\3\0\1\32\2\0\17\61\1\105"+
    "\5\61\1\122\51\61\20\0\1\32\7\0\10\32\1\123"+
    "\11\32\2\0\15\32\3\0\1\32\22\0\1\32\7\0"+
    "\17\32\1\124\2\32\2\0\15\32\3\0\1\32\22\0"+
    "\1\32\7\0\12\32\1\125\7\32\2\0\15\32\3\0"+
    "\1\32\20\0\1\126\1\0\1\32\7\0\3\32\1\127"+
    "\16\32\2\0\15\32\3\0\1\32\22\0\1\32\7\0"+
    "\22\32\2\0\3\32\1\130\11\32\3\0\1\32\22\0"+
    "\1\32\7\0\1\131\21\32\2\0\15\32\3\0\1\32"+
    "\22\0\1\32\7\0\22\32\2\0\1\32\1\132\13\32"+
    "\3\0\1\32\22\0\1\32\7\0\14\32\1\133\5\32"+
    "\2\0\15\32\3\0\1\32\22\0\1\32\7\0\10\32"+
    "\1\134\11\32\2\0\15\32\3\0\1\32\22\0\1\32"+
    "\7\0\22\32\2\0\10\32\1\135\4\32\3\0\1\32"+
    "\22\0\1\32\7\0\14\32\1\136\5\32\2\0\15\32"+
    "\3\0\1\32\22\0\1\32\7\0\1\137\21\32\2\0"+
    "\15\32\3\0\1\32\50\0\1\140\50\0\1\32\7\0"+
    "\4\32\1\141\15\32\2\0\15\32\3\0\1\32\22\0"+
    "\1\32\7\0\21\32\1\142\2\0\15\32\3\0\1\32"+
    "\22\0\1\32\7\0\22\32\2\0\10\32\1\143\4\32"+
    "\3\0\1\32\22\0\1\32\7\0\21\32\1\144\2\0"+
    "\15\32\3\0\1\32\22\0\1\32\7\0\14\32\1\145"+
    "\5\32\2\0\15\32\3\0\1\32\22\0\1\32\7\0"+
    "\22\32\2\0\3\32\1\146\11\32\3\0\1\32\20\0"+
    "\1\147\1\0\1\32\7\0\22\32\2\0\15\32\3\0"+
    "\1\32\22\0\1\32\7\0\17\32\1\150\2\32\2\0"+
    "\15\32\3\0\1\32\51\0\1\151\47\0\1\32\7\0"+
    "\2\32\1\152\17\32\2\0\15\32\3\0\1\32\22\0"+
    "\1\32\7\0\22\32\2\0\3\32\1\153\11\32\3\0"+
    "\1\32\22\0\1\32\7\0\6\32\1\154\13\32\2\0"+
    "\15\32\3\0\1\32\50\0\1\155\50\0\1\32\7\0"+
    "\4\32\1\156\15\32\2\0\15\32\3\0\1\32\47\0"+
    "\1\157\51\0\1\32\7\0\12\32\1\160\7\32\2\0"+
    "\15\32\3\0\1\32\22\0\1\32\7\0\22\32\2\0"+
    "\12\32\1\161\2\32\3\0\1\32\51\0\1\162\65\0"+
    "\1\163\60\0\1\32\7\0\1\164\21\32\2\0\15\32"+
    "\3\0\1\32\47\0\1\165\100\0\1\166\47\0\1\32"+
    "\7\0\17\32\1\167\2\32\2\0\15\32\3\0\1\32"+
    "\40\0\1\170\70\0\1\171\66\0\1\32\7\0\4\32"+
    "\1\172\15\32\2\0\15\32\3\0\1\32\51\0\1\173"+
    "\72\0\1\174\63\0\1\175\111\0\1\176\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4977];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\12\11\1\1\1\11"+
    "\2\1\1\11\3\1\2\11\11\1\3\11\2\1\3\11"+
    "\1\1\1\0\1\11\1\1\1\0\1\11\1\0\4\11"+
    "\15\1\2\11\1\0\14\1\1\11\3\1\1\0\11\1"+
    "\1\0\6\1\1\0\1\1\1\0\3\1\1\0\1\1"+
    "\1\0\2\1\2\0\1\1\2\0\1\1\2\0\1\1"+
    "\1\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline);
            }
            // fall through
          case 54: break;
          case 2:
            { 
            }
            // fall through
          case 55: break;
          case 3:
            { System.out.println("Token EXCL_CERRAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 56: break;
          case 4:
            { System.out.println("Token NUMERAL, encontrado Lexema "+ yytext());
            }
            // fall through
          case 57: break;
          case 5:
            { System.out.println("Token SIGNO_PESO, encontrado Lexema "+ yytext());
            }
            // fall through
          case 58: break;
          case 6:
            { System.out.println("Token PORCENTAJE, encontrado Lexema "+ yytext());
            }
            // fall through
          case 59: break;
          case 7:
            { System.out.println("Token AND, encontrado Lexema "+ yytext());
            }
            // fall through
          case 60: break;
          case 8:
            { System.out.println("Token PARENTESIS_ABRIR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 61: break;
          case 9:
            { System.out.println("Token PARENTESIS_CERRAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 62: break;
          case 10:
            { System.out.println("Token MULTIPLICAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 63: break;
          case 11:
            { System.out.println("Token SUMA, encontrado Lexema "+ yytext());
            }
            // fall through
          case 64: break;
          case 12:
            { System.out.println("Token COMA, encontrado Lexema "+ yytext());
            }
            // fall through
          case 65: break;
          case 13:
            { System.out.println("Token RESTA, encontrado Lexema "+ yytext());
            }
            // fall through
          case 66: break;
          case 14:
            { System.out.println("Token PUNTO, encontrado Lexema "+ yytext());
            }
            // fall through
          case 67: break;
          case 15:
            { System.out.println("Token DIVISION, encontrado Lexema "+ yytext());
            }
            // fall through
          case 68: break;
          case 16:
            { System.out.println("Token CONST_INT, encontrado Lexema "+ yytext());
            }
            // fall through
          case 69: break;
          case 17:
            { System.out.println("Token DOS_PUNTOS encontrado, Lexema "+ yytext());
            }
            // fall through
          case 70: break;
          case 18:
            { System.out.println("Token P_COMA, encontrado Lexema "+ yytext());
            }
            // fall through
          case 71: break;
          case 19:
            { System.out.println("Token MENOR_QUE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 72: break;
          case 20:
            { System.out.println("Token IGUAL, encontrado Lexema "+ yytext());
            }
            // fall through
          case 73: break;
          case 21:
            { System.out.println("Token MAYOR_QUE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 74: break;
          case 22:
            { System.out.println("Token PREG_CERRAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 75: break;
          case 23:
            { System.out.println("Token ARROBA, encontrado Lexema "+ yytext());
            }
            // fall through
          case 76: break;
          case 24:
            { System.out.println("Token ID encontrado, Lexema "+ yytext());
            }
            // fall through
          case 77: break;
          case 25:
            { System.out.println("Token CORCHETE_ABRIR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 78: break;
          case 26:
            { System.out.println("Token CORCHETE_CERRAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 79: break;
          case 27:
            { System.out.println("Token GUON_BAJO, encontrado Lexema "+ yytext());
            }
            // fall through
          case 80: break;
          case 28:
            { System.out.println("Token LLAVE_ABRIR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 81: break;
          case 29:
            { System.out.println("Token PIPE, encontrado Lexema "+ yytext());
            }
            // fall through
          case 82: break;
          case 30:
            { System.out.println("Token LLAVE_CERRAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 83: break;
          case 31:
            { System.out.println("Token CONST_STRING, encontrado Lexema "+ yytext());
            }
            // fall through
          case 84: break;
          case 32:
            { System.out.println("Token CONST_REAL, encontrado Lexema "+ yytext());
            }
            // fall through
          case 85: break;
          case 33:
            { System.out.println("Token ASIGN encontrado, Lexema "+ yytext());
            }
            // fall through
          case 86: break;
          case 34:
            { System.out.println("Token MENOR_IGUAL_QUE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 87: break;
          case 35:
            { System.out.println("Token DISTINTO, encontrado Lexema "+ yytext());
            }
            // fall through
          case 88: break;
          case 36:
            { System.out.println("Token COMPARAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 89: break;
          case 37:
            { System.out.println("Token MAYOR_IGUAL_QUE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 90: break;
          case 38:
            { System.out.println("Token IF encontrado, Lexema "+ yytext());
            }
            // fall through
          case 91: break;
          case 39:
            { System.out.println("Token EXCL_ABRIR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 92: break;
          case 40:
            { System.out.println("Token PREG_ABRIR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 93: break;
          case 41:
            { System.out.println("Token END, encontrado Lexema "+ yytext());
            }
            // fall through
          case 94: break;
          case 42:
            { System.out.println("Token INT, encontrado Lexema "+ yytext());
            }
            // fall through
          case 95: break;
          case 43:
            { /**/
            }
            // fall through
          case 96: break;
          case 44:
            { System.out.println("Token CHAR, encontrado Lexema "+ yytext());
            }
            // fall through
          case 97: break;
          case 45:
            { System.out.println("Token ELSE, encontrado Lexema "+ yytext());
            }
            // fall through
          case 98: break;
          case 46:
            { System.out.println("Token FLOAT, encontrado Lexema "+ yytext());
            }
            // fall through
          case 99: break;
          case 47:
            { System.out.println("Token PRINT encontrado, Lexema "+ yytext());
            }
            // fall through
          case 100: break;
          case 48:
            { System.out.println("Token WHILE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 101: break;
          case 49:
            { System.out.println("Token STRING, encontrado Lexema "+ yytext());
            }
            // fall through
          case 102: break;
          case 50:
            { System.out.println("Token DECLARE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 103: break;
          case 51:
            { System.out.println("Token FUNC_IGUALES, encontrado Lexema "+ yytext());
            }
            // fall through
          case 104: break;
          case 52:
            { System.out.println("Token ENDDECLARE encontrado, Lexema "+ yytext());
            }
            // fall through
          case 105: break;
          case 53:
            { System.out.println("Token BEGIN, encontrado Lexema "+ yytext());
            }
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
