
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package integrador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 39;
  public static final int MULTIPLICAR = 33;
  public static final int CORCHETE_CERRAR = 20;
  public static final int RESTA = 31;
  public static final int INT = 12;
  public static final int PARENTESIS_ABRIR = 17;
  public static final int END_PROGRAM = 9;
  public static final int AND = 15;
  public static final int IGUALES_FUNC = 23;
  public static final int OR = 16;
  public static final int END_DECLARE = 11;
  public static final int COMPARAR = 38;
  public static final int SUMA = 30;
  public static final int IF = 5;
  public static final int ID = 24;
  public static final int EOF = 0;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MAYOR_QUE = 34;
  public static final int DECLARE = 10;
  public static final int LLAVE_CERRAR = 22;
  public static final int ELSE = 6;
  public static final int LLAVE_ABRIR = 21;
  public static final int MAYOR_IGUAL_QUE = 36;
  public static final int WHILE = 4;
  public static final int BEGIN_PROGRAM = 8;
  public static final int FLOAT = 14;
  public static final int CONST_STRING = 27;
  public static final int ASIGN = 2;
  public static final int STRING = 13;
  public static final int MENOR_QUE = 35;
  public static final int CONST_REAL = 26;
  public static final int FALSE = 29;
  public static final int CORCHETE_ABRIR = 19;
  public static final int PARENTESIS_CERRAR = 18;
  public static final int DIVISION = 32;
  public static final int MENOR_IGUAL_QUE = 37;
  public static final int PRINT = 7;
  public static final int CONST_INT = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASIGN",
  "COMA",
  "WHILE",
  "IF",
  "ELSE",
  "PRINT",
  "BEGIN_PROGRAM",
  "END_PROGRAM",
  "DECLARE",
  "END_DECLARE",
  "INT",
  "STRING",
  "FLOAT",
  "AND",
  "OR",
  "PARENTESIS_ABRIR",
  "PARENTESIS_CERRAR",
  "CORCHETE_ABRIR",
  "CORCHETE_CERRAR",
  "LLAVE_ABRIR",
  "LLAVE_CERRAR",
  "IGUALES_FUNC",
  "ID",
  "CONST_INT",
  "CONST_REAL",
  "CONST_STRING",
  "TRUE",
  "FALSE",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICAR",
  "MAYOR_QUE",
  "MENOR_QUE",
  "MAYOR_IGUAL_QUE",
  "MENOR_IGUAL_QUE",
  "COMPARAR",
  "DISTINTO"
  };
}

